version: '3'
services:
  myapp:
    container_name: docker-myapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./stock_market_dataset:/app/stock_market_dataset
      - ./:/app/
